# Generated by Django 4.1.7 on 2023-02-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='подсказка, если применимо', verbose_name='Описание')),
                ('priority', models.IntegerField(db_index=True, default=1, verbose_name='Приоритет сортировки')),
                ('bone', models.DateTimeField(blank=True, null=True, verbose_name='Выполено')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Список дел',
                'ordering': ('priority', 'created'),
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
    ]
