# Generated by Django 4.1.7 on 2023-02-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bone',
            new_name='done',
        ),
    ]
