# Generated by Django 4.1.7 on 2023-03-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_alter_item_user_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemresult',
            name='item',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ItemResult',
        ),
    ]
